export enum ROUTES {
  ONBOARDING = "Onboarding",
  LOGIN = "Login",
  REGISTER = "Register",
  DASHBOARD = "Dashboard",
  FORGOTPASSWORD = "ForgotPassword",
  REMINDERS = "Reminders",
  PROFILE = "Profile",
  CHANGEPASSWORD = "ChangePassword",
  CREATENOTE = "CreateNote",
  RESETPASSWORD = "ResetPassword",
  VIEWPROFILE = "ViewProfile",
  EDITPROFILE = "EditProfile",
  GUESTCONVERSION = "GuestConversion",
  NOTESPASSWORD = "NotesPassword",
  CHANGENOTEPASSWORD = "ChangeNotePassword",
}
